import Cloud_Background from '../imgs/background.png';
import BitgetIcon from '../imgs/bitget.png';
import BingXIcon from '../imgs/bingx.png';
import GateioIcon from '../imgs/gateio.png';
import BitMartIcon from '../imgs/bitmart.png';
import LBankIcon from '../imgs/lbank.png';
import WeexIcon from '../imgs/weex.png';
import BiconomyIcon from '../imgs/biconomy.png';
import RaydiumIcon from '../imgs/raydium.png';
import MEXCIcon from '../imgs/mexc.png';
import CoinWIcon from '../imgs/coinw.png';
import PhantomIcon from '../imgs/phantom.png';
import SolanaIcon from '../imgs/solana.png';
import RadiyumIcon from '../imgs/Radiyum.png';
import CoffeeLabubuIcon from '../imgs/cofeeLabubu.png';
import DollIcon from '../imgs/doll-1.png';
import LabubuImg from '../imgs/labubuImg.png';
import WLabubuImg from '../imgs/w-labubu.png';
import TitleImg from '../imgs/title.png';
import MainTitleImg from '../imgs/mainTitle.png';
import FooterLabubu from '../imgs/footerlabubu.png';
import HowTo from '../imgs/howtolabubu.png';
import WhoWeAre from '../imgs/whoweare.png';
import WhoWeLabubu from '../imgs/whowelabubu.png';
import JoinUs from '../imgs/joinus.png';
import Ibank from '../imgs/lbank.png';
import LabubuToken from '../imgs/token.png';

export const Background = Cloud_Background;
export const Bitget = BitgetIcon;
export const BingX = BingXIcon;
export const Gateio = GateioIcon;
export const BitMart = BitMartIcon;
export const LBank = LBankIcon;
export const Weex = WeexIcon;
export const Biconomy = BiconomyIcon;
export const Raydium = RaydiumIcon;
export const MEXC = MEXCIcon;
export const CoinW = CoinWIcon;
export const Phantom = PhantomIcon;
export const Solana = SolanaIcon;
export const Radiyum = RadiyumIcon;
export const CoffeeLabubu = CoffeeLabubuIcon;
export const Doll = DollIcon;
export const LabubuIcon = LabubuImg;
export const WLabubuIcon = WLabubuImg;
export const Title = TitleImg;
export const MainTitle = MainTitleImg;
export const FooterLabubuIcon = FooterLabubu;
export const HowToLabubu = HowTo;
export const WhoWeAreIcon = WhoWeAre;
export const WhoWeLabubuIcon = WhoWeLabubu;
export const JoinUsIcon = JoinUs;
export const IbankIcon = Ibank;
export const LabubuTokenIcon = LabubuToken;